config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  get '/about' => 'pages#about'

  resources :divers , except: [:new, :destroy]

  get '/register', to: 'divers#new'

  resources :fires do
    member do
      post 'like'
    end
  end

  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  get 'logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :objectives, only: [:new, :create, :show]

end

app/models/diver.rb
class Diver < ActiveRecord::Base
	has_many :fires
	has_many :likes
	before_save {self.email = email.downcase}
	validates :divername, presence: true, length: {minimum: 3, maximum: 40}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 110},
									  uniqueness: { case_sensitive: false },
									  format: {with: VALID_EMAIL_REGEX}
	has_secure_password
	has_attached_file :image, :styles => { :medium => "300x400>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/fire.rb
class Fire < ActiveRecord::Base
	belongs_to :diver
	has_many :likes, dependent: :destroy
	has_many :fire_styles, dependent: :destroy	
	has_many :styles, through: :fire_styles
	has_many :fire_objectives, dependent: :destroy
	has_many :objectives, through: :fire_objectives

	validates :name, presence: true, length: {minimum: 5, maximum: 100}
	validates :summary, presence: true, length: {minimum: 10, maximum: 150}
	validates :description, presence: true, length: {minimum: 20, maximum: 500}
	validates :diver_id, presence: true
	mount_uploader :picture, PictureUploader
	validate :picture_size
	default_scope -> { order(created_at: :asc) }

	def thumbs_up_total
		self.likes.where(like: true).size
	end

	def thumbs_down_total
		self.likes.where(like: false).size
	end

	private

		def picture_size
			if picture.size > 5.megabytes
				errors.add(:picture, "should be less than 5MB")
			end
		end	
end

app/models/fire_objective.rb
class FireObjective < ActiveRecord::Base
	belongs_to :objective
	belongs_to :fire
end

app/models/fire_style.rb
class FireStyle < ActiveRecord::Base
	belongs_to :fire
	belongs_to :style
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :diver
	belongs_to :fire

	validates_uniqueness_of :diver, scope: :fire
end

app/models/objective.rb
class Objective < ActiveRecord::Base
	validates :name, presence: true, length: { minimum: 2, maximum: 25 }
	has_many :fire_objectives
	has_many :fires, through: :fire_objectives
end

app/models/style.rb
class Style < ActiveRecord::Base
	validates :name, presence: true, length: { minimum: 2, maximum: 25 }, uniqueness: { case_sensitive: false }
	has_many :fire_styles
	has_many :fires, through: :fire_styles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in? #makes the methods available to views

  def current_user
  	@current_user ||= Diver.find(session[:diver_id]) if session[:diver_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = 'You need to log in to do that'
      redirect_to login_path
    end
  end

end

app/controllers/divers_controller.rb
class DiversController < ApplicationController
	before_action :set_diver, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update]

	def index
		@divers = Diver.paginate(page: params[:page], per_page: 5)
	end

	def new
		@diver = Diver.new
	end

	def show
		@fires = @diver.fires.paginate(page: params[:page], per_page: 3)
	end

	def create
		@diver = Diver.new(diver_params)
		if @diver.save
			flash[:success] = 'Your account has been created successfully'
			session[:diver_id] = @diver.id
			redirect_to diver_path(@diver)
		else 
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @diver.update(diver_params)
			flash[:success] = 'Your profile has been successfully updated'
			redirect_to diver_path(diver) 
		else
			render 'new'
		end
	end


	private

		def diver_params
			params.require(:diver).permit(:divername, :email, :image, :password)
		end

		def set_diver
			@diver = Diver.find(params[:id])
		end

		def require_same_user
			if current_user != @diver and !current_user.admin?
				flash[:danger] = "You can only edit your own profile"
				redirect_to root_path
			end
		end

end

app/controllers/fires_controller.rb
class FiresController < ApplicationController
	before_action :set_fire, only: [:edit, :update, :show, :like]
	before_action :require_user, except: [:show, :index, :like]
	before_action :require_same_user, only: [:edit, :update]
	before_action :require_user_like, only: [:like]
	before_action :admin_user, only: :destroy

	def index 
		@fires = Fire.paginate(page: params[:page], per_page: 5)
	end

	def show
	end

	def new
		@fire = Fire.new
	end

	def create
		@fire = Fire.new(fire_params)
		@fire.diver = current_user

		if @fire.save
			flash[:success] = "Your Fire was created successfully"
			redirect_to fires_path
		else
			flash[:success] = "Your Fire failed to successfully post"
			render :new
		end
	end

	def edit
	end

	def update
		if @fire.update(fire_params)
			flash[:success] = "Successfully updated your Fire!"
			redirect_to fire_path(@fire)
		else
			render :edit
		end
	end

	def like
		
		like = Like.create(like: params[:like], diver: current_user, fire: @fire)
		if like.valid?
			flash[:success] = "Voted! XD"
			redirect_to :back
		else
			flash[:danger] = "You already voted on this Fire!"
			redirect_to :back
		end
	end

	def destroy
		Fire.find(params[:id]).destroy
		flash[:success] = "She's gone...it's done."
		redirect_to fires_path
	end

	private

		def fire_params
			params.require(:fire).permit(:name, :summary, :description, :picture, style_ids: [], objective_ids: [])
		end

		def set_fire
			@fire = Fire.find(params[:id])
		end

		def require_same_user
			if current_user != @fire.diver and !current_user.admin?
				flash[:danger] = "You can only edit when logged in"
				redirect_to root_path
			end
		end

		def require_user_like
			if !logged_in?
				flash[:danger] = 'You need to log in to do that'
				redirect_to :back
			end
		end

		def admin_user
			redirect_to fires_path unless current_user.admin?
		end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController 
	
	def new
		
	end

	def create
		diver = Diver.find_by(email: params[:email])
		if diver && diver.authenticate(params[:password])
			session[:diver_id] = diver.id
			flash[:success] = "Successfully Logged In!"
			redirect_to fires_path
		else
			flash.now[:danger] = "Your email or password does not match"
			render 'new'
		end
	end

	def destroy
		session[:diver_id] = nil
		flash[:success] = "Logged Out"
		redirect_to root_path
	end
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
	before_action :require_user, except: [:show]
	def new
		@objective = Objective.new
	end

	def create
		@objective = Objective.new(obj_params)
		if @objective.save
			flash[:success] = "Objective Added :D"
			redirect_to fires_path
		else
			render 'new'
		end
	end

	def show
		@objective = Objective.find(params[:id])
		@fires = @objective.fires.paginate(page: params[:page], per_page: 4)
	end


	private

		def obj_params
			params.require(:objective).permit(:name)
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


	def home
		redirect_to fires_path if logged_in?
	end
	
	def about
	end
	
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
	before_action :require_user, except: [:show]
	def new
		@style = Style.new
	end

	def create
		@style = Style.new(style_params)
		if @style.save
			flash[:success] = "Style Added :D"
			redirect_to fires_path
		else
			render 'new'
		end
	end

	def show
		@style = Style.find(params[:id])
		@fires = @style.fires.paginate(page: params[:page], per_page: 4)
	end
	
	private

		def style_params
			params.require(:style).permit(:name)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(diver, options = { size: 80 } )
		gravatar_id = Digest::MD5::hexdigest(diver.email.downcase)
		size = options[:size]
		gravatar_url = "http://secure.gravatar.com/avatare/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: diver.divername, class: "gravatar")
	end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/divers/_display.html.erb
<%= will_paginate  %>

<% @fire.each do |fire| %>
	<div class="row">

		<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 well">

			<div class="col-sm-6 col-md-2">
				<section class="diver_info center">
					<%= image_tag(fire.diver.image.url(:thumb), class: 'img-responsive') %>
					<h5>Diver Name: <%= fire.diver.divername %></h5>
				</section>
			</div>

			<div class='col-sm-6 col-md-3' style='float: right'>
					<div class='like pull-left'>
						<%= link_to like_fire_path(fire, like: true), method: :post do %>
						<button type='button' class='btn btn-info btn-lg'>
							<i class='glyphicon glyphicon-thumbs-up'></i>
						</button>
						<% end %> &nbsp;<%= fire.thumbs_up_total %>&nbsp;&nbsp; 
					</div>

					<div class='like pull-right'>
						<%= link_to like_fire_path(fire, like: false), method: :post do %>
						<button type='button' class='btn btn-danger btn-lg'>
							<i class='glyphicon glyphicon-thumbs-down'></i>
						</button>
						<% end %> &nbsp; <%= fire.thumbs_down_total %>
					</div>	\

					<p class='edition', style='float: right'>
						<span class='quiet'><small>created <%= time_ago_in_words(fire.created_at) %> ago </small></span>  <br/>
						<span class='quiet'><small> updated <%= time_ago_in_words(fire.updated_at) %> ago </small></span>
				</p>
			</div>
				
			<div class="col-md-7">

				<h3> <%= link_to fire.name, fire_path(fire), class: "post-title center-block" %> </h3>
				<h5 class="post-summary"> <%= fire.summary %> </h5>
			</div>
			 	
			<div class='center-block'>
				<%= image_tag(fire.picture.url, class: "img-responsive") if fire.picture? %>
			</div>		

		</div>
	
		
	</div>
<% end %>

<%= will_paginate %>

app/views/divers/_form.html.erb
<div class='row col-sm-12 '>
	<div class='well col-xs-12 col-md-8 col-md-offset-2 '>
		<%= form_for @diver, :url => divers_path, :html => { :multipart => true } do |f| %>

			<%= f.label :divername %> <br/>
			<%= f.text_field :divername %> <br/><br/>

			<%= f.label :email %> <br/>
			<%= f.email_field :email %> <br/><br/>

			<%= f.label :password %>
			<%= f.password_field :password %> <br/><hr/>
			
			<%= f.label :profile_picture %>
			<%= f.file_field :image %>
 	
			<%= f.submit(@diver.new_record? ? 'Register' : 'Edit Profile', class: 'btn btn-danger') %> <br/>

		<% end %>
	</div>
</div>

app/views/divers/edit.html.erb
<%= render 'shared/page_title', title: 'Edit Your Profile' %>

<%= render 'form' %>

app/views/divers/index.html.erb
<%= render 'shared/page_title', title: 'All Divers' %>

<ul class="nav nav-tabs">
	<li>
		<%= link_to 'Fires', fires_path %>
	</li>

	<li class='active'>
		<%= link_to 'Divers', divers_path %>
	</li>
	
</ul>

<div class='row'>
	<div class='col-md-4 pull-left'>
		<%= will_paginate %>
	</div>
</div>

<% @divers.each do |diver| %>
	<div class='row'>
		<div class='col-md-10 col-md-offset-1 well center'>
			<%= link_to(image_tag(diver.image.url(:medium)), diver_path(diver), class: 'pull-right') %>

			<h2 class='diver-stats'> Diver Name: <%= diver.divername %> </h1>

			<h2 class='diver-stats'> Dives Logged: <%= diver.fires.count %> </h2>

			<h2 class='diver-stats'> Active Since: <%= time_ago_in_words(diver.created_at) %> </h2>
		</div>
	</div>

<% end %>

app/views/divers/new.html.erb
<%= render 'shared/page_title', title: 'Register Your Account' %>
<%= render 'shared/errors', obj: @diver %>
<%= render 'form' %>

app/views/fires/edit.html.erb
<%= render 'shared/page_title', title: 'Edit Fire' %>

<%= render 'form' %>

app/views/fires/index.html.erb
<%= render 'shared/page_title', title: 'All Fires' %>

<ul class="nav nav-tabs">
	<li class='active'>
		<%= link_to 'Fires', fires_path %>
	</li>
	<li>
		<%= link_to 'Divers', divers_path %>
	</li>
</ul>



<%= will_paginate @fires %>

<% @fires.each do |fire| %>
	<div class="row">

		<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 well">

			<div class="col-sm-2 col-md-2 col-xs-2">
				<section class="diver_info center">
					<%= image_tag(fire.diver.image.url(:medium), class: 'img-responsive') %>
					<h5>Diver Name: <%= link_to(fire.diver.divername, diver_path(fire.diver)) %></h5>
				</section>
			</div>

			<div class='col-xs-3 col-sm-3 col-md-3 col-lg-2' style='float: right'>
					<div class='like pull-left'>
						<%= link_to like_fire_path(fire, like: true), method: :post do %>
						<button type='button' class='btn btn-info btn-lg img-responsive'>
							<i class='glyphicon glyphicon-thumbs-up img-responsive'></i>
						</button>
						<% end %> &nbsp;<%= fire.thumbs_up_total %>&nbsp;&nbsp; 
					</div>

					<div class='like pull-right'>
						<%= link_to like_fire_path(fire, like: false), method: :post do %>
						<button type='button' class='btn btn-danger btn-lg img-responsive'>
							<i class='glyphicon glyphicon-thumbs-down img-responsive'></i>
						</button>
						<% end %> &nbsp; <%= fire.thumbs_down_total %>
					</div>	

					<p class='edition', style='float: right'>
						<span class='quiet'><small>created <%= time_ago_in_words(fire.created_at) %> ago </small></span> 
						<span class='quiet'><small>updated <%= time_ago_in_words(fire.updated_at) %> ago </small></span>
				</p>
			</div>
				
			<div class="col-xs-4 col-sm-4 col-md-5">

				<h3> <%= link_to fire.name, fire_path(fire), class: "post-title center-block" %> </h3>
				<h5 class="post-summary"> <%= fire.summary %> </h5>
				<% if fire.styles.any? %>
					<p> Dive Style: <%= render fire.styles %> </p>
				<% end %>
				<% if fire.objectives.any? %>
					<p> Dive Objectives: <%= render fire.objectives %> </p>
				<% end %>
			</div>
			 	
			<div class='center-block'>
				<%= image_tag(fire.picture.url, class: "img-responsive") if fire.picture? %>
			</div>		

		</div>
	
		
	</div>
<% end %>

<%= will_paginate @fires %>

app/views/fires/new.html.erb
<%= render 'shared/page_title', title: 'Create New Fire' %> 

<p id='new-fire-how-to' style='text-align: center'> Have an interesting dive experience, underwater encounter, or flight fuckup? <br/> Write about it here and watch the flames rise </p>
<hr/>

<%= render 'form' %>

app/views/fires/show.html.erb
<%= render 'shared/page_title', title: @fire.name %>

<div class='row'>
	<div class='col-md-4 pull-right center'>
	 <p>
	 	<h5> Brought to you by: <%= link_to(@fire.diver.divername, diver_path(@fire.diver)) %></h5>
	 	<%= image_tag(@fire.diver.image.url(:medium)) %>
	 </p>
	</div>
	
	<div class='col-md-8'>
		
		<h3><%= @fire.summary %> </h3>
		<div class="show_fire">
			<%= image_tag(@fire.picture.url, class: "gravatar") if @fire.picture %>
		</div>
		<div class='well'>
		<p>
		<% if @fire.styles.any? %>
			<p> Dive Style: <%= render @fire.styles %> </p>
		<% end %>
		<% if @fire.objectives.any? %>
			<p> Dive Objectives: <%= render @fire.objectives %> </p>
		<% end %>
			<strong> So this is what happened: </strong>
		</p>

		<%= simple_format(@fire.description) %>
		<div class='pull-right'>
			<%= link_to like_fire_path(@fire, like: true), method: :post do %>
				<i class='glyphicon glyphicon-thumbs-up'></i>
			<% end %> &nbsp;<%= @fire.thumbs_up_total %>&nbsp;&nbsp; 
			
			<%= link_to like_fire_path(@fire, like: false), method: :post do %>
				<i class='glyphicon glyphicon-thumbs-down'></i>
			<% end %> &nbsp; <%= @fire.thumbs_down_total %>
		</div>
	</div>
</div>
</div>

<div class='col-md-4 col-md-offset-2 col-lg-4 col-lg-offset-2'>

<h5> <%= link_to "Return to Browsing Fires", fires_path, class: 'btn btn-info pull-left' %> &nbsp; 

<% if logged_in? and (@fire.diver == current_user || current_user.admin?) %> <%= link_to "Edit this Fire", edit_fire_path(@fire), class: 'btn btn-info pull-right' %> </h5> <% end %>

<% if logged_in? and current_user.admin? %>
	<%= link_to "Delete Fire", @fire, method: :delete, data: {confirm: "You Sure M8?" } %>
<% end %>

</div>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<body>
<nav class="head-nav">
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example navbar collapse-1">
		  <span class="sr only"> Toggle Nav </span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		</button>
		<a><%= link_to(image_tag('seasfire.png'), root_path) %> </a>

		</div>
	<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
        
        <li><%= link_to 'About', about_path, :class => 'nav-options' %></a></li>
        <li><%= link_to 'Browse Fires', fires_path, :class => 'nav-options' %></li>
        
        <li class="nav-options">
          <a href="#" class="nav-options" data-toggle="dropdown" role="button" aria-expanded="false"> Create A New... <span class="caret"></span></a>
          
          <ul class="dropdown-menu" role="menu">
            
            <% if logged_in? %>
              <li><%= link_to('All Diver Profiles', divers_path) %> </li>
              <li><%= link_to('Add Fires', new_fire_path) %></li>

              <li class='divider'></li>
              <li><%= link_to(new_style_path) do %> New Style <% end %> </li>
              <li><%= link_to('Add Objective', new_objective_path) %></li>
              <li class="divider"></li>
              <li><%= link_to('Log out', logout_path) %></a></li>
            <% else %>
              <li> <%= link_to('Log in', login_path) %> </li>
              <li> <%= link_to('Sign up', register_path) %> </li>
            <% end %>

          </ul>

          <% if logged_in? %>
          <li> <%= link_to("Logged In As: " + current_user.divername, diver_path(current_user))%> </li>
        <% end %>
        </li>
      </ul>
</nav>
<body>
</html>

app/views/objectives/_objective.html.erb
<span class='quiet'><small> <%= link_to objective.name, objective_path(objective) %> </small></span> 

app/views/objectives/show.html.erb
<%= render 'shared/page_title', title: "Dives for: " + @objective.name %>

<ul class="nav nav-tabs">
	<li class='active'>
		<%= link_to 'Fires', fires_path %>
	</li>
	<li>
		<%= link_to 'Divers', divers_path %>
	</li>
</ul>



<%= will_paginate @fires %>

<% @objective.fires.each do |fire| %>
	<div class="row">

		<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 well">

			<div class="col-sm-2 col-md-2 col-xs-2">
				<section class="diver_info center">
					<%= image_tag(fire.diver.image.url(:medium), class: 'img-responsive') %>
					<h5>Diver Name: <%= link_to(fire.diver.divername, diver_path(fire.diver)) %></h5>
				</section>
			</div>

			<div class='col-xs-3 col-sm-3 col-md-3 col-lg-2' style='float: right'>
					<div class='like pull-left'>
						<%= link_to like_fire_path(fire, like: true), method: :post do %>
						<button type='button' class='btn btn-info btn-lg img-responsive'>
							<i class='glyphicon glyphicon-thumbs-up img-responsive'></i>
						</button>
						<% end %> &nbsp;<%= fire.thumbs_up_total %>&nbsp;&nbsp; 
					</div>

					<div class='like pull-right'>
						<%= link_to like_fire_path(fire, like: false), method: :post do %>
						<button type='button' class='btn btn-danger btn-lg img-responsive'>
							<i class='glyphicon glyphicon-thumbs-down img-responsive'></i>
						</button>
						<% end %> &nbsp; <%= fire.thumbs_down_total %>
					</div>	

					<p class='edition', style='float: right'>
						<span class='quiet'><small>created <%= time_ago_in_words(fire.created_at) %> ago </small></span> 
						<span class='quiet'><small>updated <%= time_ago_in_words(fire.updated_at) %> ago </small></span>
				</p>
			</div>
				
			<div class="col-xs-4 col-sm-4 col-md-5">

				<h3> <%= link_to fire.name, fire_path(fire), class: "post-title center-block" %> </h3>
				<h5 class="post-summary"> <%= fire.summary %> </h5>
				<p> Dive Style: <%= render fire.styles %> </p>
				<p> Dive Objectives: <%= render fire.objectives %> </p>
			</div>
			 	
			<div class='center-block'>
				<%= image_tag(fire.picture.url, class: "img-responsive") if fire.picture? %>
			</div>		

		</div>
	
		
	</div>
<% end %>

<%= will_paginate @fires %>

app/views/shared/_display.html.erb
<%= will_paginate obj %>

<% obj.each do |fire| %>
	<div class="row">

		<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 well">

			<div class="col-sm-6 col-md-2">
				<section class="diver_info center">
					<%= image_tag(fire.diver.image.url(:thumb), class: 'img-responsive') %>
					<h5>Diver Name: <%= fire.diver.divername %></h5>
				</section>
			</div>

			<div class='col-sm-6 col-md-3' style='float: right'>
					<div class='like pull-left'>
						<%= link_to like_fire_path(fire, like: true), method: :post do %>
						<button type='button' class='btn btn-info btn-lg'>
							<i class='glyphicon glyphicon-thumbs-up'></i>
						</button>
						<% end %> &nbsp;<%= fire.thumbs_up_total %>&nbsp;&nbsp; 
					</div>

					<div class='like pull-right'>
						<%= link_to like_fire_path(fire, like: false), method: :post do %>
						<button type='button' class='btn btn-danger btn-lg'>
							<i class='glyphicon glyphicon-thumbs-down'></i>
						</button>
						<% end %> &nbsp; <%= fire.thumbs_down_total %>
					</div>	\

					<p class='edition', style='float: right'>
						<span class='quiet'><small>created <%= time_ago_in_words(fire.created_at) %> ago </small></span>  <br/>
						<span class='quiet'><small> updated <%= time_ago_in_words(fire.updated_at) %> ago </small></span>
				</p>
			</div>
				
			<div class="col-md-7">

				<h3> <%= link_to fire.name, fire_path(fire), class: "post-title center-block" %> </h3>
				<h5 class="post-summary"> <%= fire.summary %> </h5>
			</div>
			 	
			<div class='center-block'>
				<%= image_tag(fire.picture.url, class: "img-responsive") if fire.picture? %>
			</div>		

		</div>
	
		
	</div>
<% end %>

<%= will_paginate %>

app/views/shared/_page_title.html.erb
<p>
	<h1 class='fire-title'> <%= title %> </h1>
	<hr/>
</p>

app/views/styles/_style.html.erb
<span class='quiet'><small> <%= link_to style.name, style_path(style) %> </small></span> 

app/views/styles/index.html.erb
<h1> Index Page </h1>

app/views/styles/show.html.erb
<%= render 'shared/page_title', title: "Dives for: " + @style.name %>

<ul class="nav nav-tabs">
	<li class='active'>
		<%= link_to 'Fires', fires_path %>
	</li>
	<li>
		<%= link_to 'Divers', divers_path %>
	</li>
</ul>



<%= will_paginate @fires %>

<% @style.fires.each do |fire| %>
	<div class="row">

		<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 well">

			<div class="col-sm-2 col-md-2 col-xs-2">
				<section class="diver_info center">
					<%= image_tag(fire.diver.image.url(:medium), class: 'img-responsive') %>
					<h5>Diver Name: <%= link_to(fire.diver.divername, diver_path(fire.diver)) %></h5>
				</section>
			</div>

			<div class='col-xs-3 col-sm-3 col-md-3 col-lg-2' style='float: right'>
					<div class='like pull-left'>
						<%= link_to like_fire_path(fire, like: true), method: :post do %>
						<button type='button' class='btn btn-info btn-lg img-responsive'>
							<i class='glyphicon glyphicon-thumbs-up img-responsive'></i>
						</button>
						<% end %> &nbsp;<%= fire.thumbs_up_total %>&nbsp;&nbsp; 
					</div>

					<div class='like pull-right'>
						<%= link_to like_fire_path(fire, like: false), method: :post do %>
						<button type='button' class='btn btn-danger btn-lg img-responsive'>
							<i class='glyphicon glyphicon-thumbs-down img-responsive'></i>
						</button>
						<% end %> &nbsp; <%= fire.thumbs_down_total %>
					</div>	

					<p class='edition', style='float: right'>
						<span class='quiet'><small>created <%= time_ago_in_words(fire.created_at) %> ago </small></span> 
						<span class='quiet'><small>updated <%= time_ago_in_words(fire.updated_at) %> ago </small></span>
				</p>
			</div>
				
			<div class="col-xs-4 col-sm-4 col-md-5">

				<h3> <%= link_to fire.name, fire_path(fire), class: "post-title center-block" %> </h3>
				<h5 class="post-summary"> <%= fire.summary %> </h5>
				<p> Dive Style: <%= render fire.styles %> </p>
				<p> Dive Objectives: <%= render fire.objectives %> </p>
			</div>
			 	
			<div class='center-block'>
				<%= image_tag(fire.picture.url, class: "img-responsive") if fire.picture? %>
			</div>		

		</div>
	
		
	</div>
<% end %>

<%= will_paginate @fires %>